// Form: the stuff needed
// name, selected lists of classes taken and the difficulty of each class,
// list of interests and their difficultys, selection for CS specialization
// Quarters left till graditiaton

import { useForm, useFieldArray } from "react-hook-form";
import { useEffect, useState } from "react";
import { CheckCircle } from "lucide-react";
import useApiPost from "../hooks/useApiPost";
import useApiGet from "../hooks/useApiGet";
import { ReadCookie } from "./CookieUtils";
import UserInterestsForm from "./UserInterestsForm";
import UserClassesForm from "./UserClassesForm";

export default function UserSettingsForm( ) {
  const {
    register,
    control,
    handleSubmit,
    reset, // <-- This function can force-update the entire form at once (Added by Gemini AI)
  } = useForm({
    defaultValues: {
      completedClasses: [],
      interests: [],
      username: ReadCookie("username") || "",
      quartersLeft: 0,
      specialization: "",
      easierClasses: false,
    },
  });

  const [settingsPage, setSettingsPage] = useState("Interests");
  const [showNotification, setShowNotification] = useState(false);

  const {
    fields: completedClasses,
    append: completedClassesAppend,
    remove: completedClassesRemove,
  } = useFieldArray({
    control,
    name: "completedClasses",
  });

  const {
    fields: interests,
    append: interestsAppend,
    remove: interestsRemove,
  } = useFieldArray({
    control,
    name: "interests",
  });

  const { execute: getUserInfo, response: userInfoResponse } = useApiGet({
    api: "/api/getUserInfo",
  });

  const { execute: sendUserInfo } = useApiPost({
    api: "/api/setUserInfo",
  });

  // this gets the class info when the settings page first comes up
  // so we can populate the drop down menu for the user to select
  const { execute: getAllClassesData, response: classListResponse } = useApiGet(
    {
      api: "/api/allClassesData",
    },
  );

  const { execute: getInterestsList, response: interestsListResponse } =
    useApiGet({
      api: "/api/interestsList",
    });

  const {
    execute: getSpecializationInfo,
    response: specializationListResponse,
  } = useApiGet({
    api: "/api/specializationInfo",
  });

  const onSubmit = async (data) => {
    console.log("Clean JSON data:", data);
    // if the user is not logged in, save the data to local storage (generated with gemini ai)
    if (!data.username) {
      console.log("No user logged in, saving to local storage");
      localStorage.setItem("userSettings", JSON.stringify(data));
      setShowNotification(true);
      setTimeout(() => setShowNotification(false), 3000);
    } else {
      try {
        await sendUserInfo(data);
        setShowNotification(true);
        setTimeout(() => setShowNotification(false), 3000);
      } catch (error) {
        console.error("Failed to save user info:", error);
      }
    }
  };

  useEffect(() => {
    getAllClassesData();
    getInterestsList();
    getSpecializationInfo();
    // Use the ReadCookie helper to get the username from document.cookie
    const username = ReadCookie("username");
    getUserInfo({ params: { username: username } });
  }, [getAllClassesData, getInterestsList, getSpecializationInfo, getUserInfo]);

  // This logic was generated by Gemini AI to handle auto-populating saved data
  // When reset(data) is called, it finds all registered inputs matching the
  // keys in your JSON (interests, specialization, and even the 'classes' array)
  // and updates them to match the new values.
  useEffect(() => {
    if (userInfoResponse?.data) {
      reset(userInfoResponse.data);
    } else if (!ReadCookie("username")) {
      // If guest user, try to load from local storage (genereated with geminii)
      const localData = localStorage.getItem("userSettings");
      if (localData) {
        console.log("Loading guest settings from local storage");
        reset(JSON.parse(localData));
      }
    }
  }, [userInfoResponse, reset]);

  return (
    <div>
      <h2 className="text-3xl font-extrabold text-slate-900 mb-6 tracking-tight">
        User Settings
      </h2>
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-6">
        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 bg-slate-50 p-4 rounded-xl border border-slate-100">
          <label className="text-sm font-semibold text-slate-500 uppercase tracking-wide">
            User ID:
          </label>
          <input
            type="text"
            {...register("username")}
            className="text-lg font-bold text-slate-900 bg-transparent outline-none flex-1"
            readOnly
          />
        </div>

        <div className="flex bg-slate-100 p-1 rounded-xl w-fit">
          <button
            type="button"
            className={`px-6 py-2 rounded-lg font-semibold text-sm transition-all ${settingsPage === "Interests" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
            onClick={() => setSettingsPage("Interests")}
          >
            Interests
          </button>
          <button
            type="button"
            className={`px-6 py-2 rounded-lg font-semibold text-sm transition-all ${settingsPage === "Classes" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
            onClick={() => setSettingsPage("Classes")}
          >
            Classes
          </button>
        </div>

        {settingsPage === "Interests" ? (
          <UserInterestsForm
            register={register}
            interests={interests}
            interestsAppend={interestsAppend}
            interestsRemove={interestsRemove}
            interestsListResponse={interestsListResponse}
          />
        ) : (
          <UserClassesForm
            register={register}
            completedClasses={completedClasses}
            completedClassesAppend={completedClassesAppend}
            completedClassesRemove={completedClassesRemove}
            classListResponse={classListResponse}
            specializationListResponse={specializationListResponse}
          />
        )}

        <div className="relative mt-4">
          <button
            type="submit"
            className="w-full bg-indigo-600 text-white py-4 px-6 rounded-xl font-bold hover:bg-indigo-700 transition-all cursor-pointer shadow-sm hover:shadow-md active:scale-[0.98] active:shadow-inner"
          >
            Save Changes
          </button>
        </div>
      </form>

      {showNotification && (
        <div className="fixed top-6 right-6 z-[60] flex items-center gap-3 bg-white border border-slate-100 text-slate-800 px-5 py-3.5 rounded-xl shadow-2xl animate-in slide-in-from-top-5 fade-in duration-300 pointer-events-none">
          <CheckCircle className="w-5 h-5 text-green-500" />
          <span className="font-semibold text-sm tracking-wide">
            Settings saved successfully!
          </span>
        </div>
      )}
    </div>
  );
}
