// Form: the stuff needed
// name, selected lists of classes taken and the difficulty of each class,
// list of interests and their difficultys, selection for CS specialization
// Quarters left till graditiaton

import { useForm, useFieldArray } from "react-hook-form";
import { useEffect, useState } from "react";
import useApiPost from "../hooks/useApiPost";
import useApiGet from "../hooks/useApiGet";
import { ReadCookie } from "./CookieUtils";
import UserInterestsForm from "./UserInterestsForm";
import UserClassesForm from "./UserClassesForm";

export default function UserSettingsForm({ setDisplaySettingsPage }) {
  const {
    register,
    control,
    handleSubmit,
    reset, // <-- This function can force-update the entire form at once (Added by Gemini AI)
  } = useForm({
    defaultValues: {
      completedClasses: [],
      interests: [],
      username: ReadCookie("username") || "",
      quartersLeft: 0,
      specialization: "",
    },
  });

  const [settingsPage, setSettingsPage] = useState("Interests");

  const {
    fields: completedClasses,
    append: completedClassesAppend,
    remove: completedClassesRemove,
  } = useFieldArray({
    control,
    name: "completedClasses",
  });

  const {
    fields: interests,
    append: interestsAppend,
    remove: interestsRemove,
  } = useFieldArray({
    control,
    name: "interests",
  });

  const { execute: getUserInfo, response: userInfoResponse } = useApiGet({
    api: "/api/getUserInfo",
  });

  const { execute: sendUserInfo } = useApiPost({
    api: "/api/setUserInfo",
  });

  // this gets the class info when the settings page first comes up
  // so we can populate the drop down menu for the user to select
  const { execute: getAllClassesData, response: classListResponse } = useApiGet(
    {
      api: "/api/allClassesData",
    },
  );

  const { execute: getInterestsList, response: interestsListResponse } =
    useApiGet({
      api: "/api/interestsList",
    });

  const {
    execute: getSpecializationInfo,
    response: specializationListResponse,
  } = useApiGet({
    api: "/api/specializationInfo",
  });

  const onSubmit = (data) => {
    setDisplaySettingsPage(false);
    console.log("Clean JSON data:", data);
    // if the user is not logged in, save the data to local storage (generated with gemini ai)
    if (!data.username) {
      console.log("No user logged in, saving to local storage");
      localStorage.setItem("userSettings", JSON.stringify(data));
    } else {
      sendUserInfo(data);
    }
  };

  useEffect(() => {
    getAllClassesData();
    getInterestsList();
    getSpecializationInfo();
    // Use the ReadCookie helper to get the username from document.cookie
    const username = ReadCookie("username");
    getUserInfo({ params: { username: username } });
  }, [getAllClassesData, getInterestsList, getSpecializationInfo, getUserInfo]);

  // This logic was generated by Gemini AI to handle auto-populating saved data
  // When reset(data) is called, it finds all registered inputs matching the
  // keys in your JSON (interests, specialization, and even the 'classes' array)
  // and updates them to match the new values.
  useEffect(() => {
    if (userInfoResponse?.data) {
      reset(userInfoResponse.data);
    } else if (!ReadCookie("username")) {
      // If guest user, try to load from local storage (genereated with geminii)
      const localData = localStorage.getItem("userSettings");
      if (localData) {
        console.log("Loading guest settings from local storage");
        reset(JSON.parse(localData));
      }
    }
  }, [userInfoResponse, reset]);

  return (
    <div>
      <h2 className="text-3xl font-extrabold text-slate-900 mb-6 tracking-tight">
        User Settings
      </h2>
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-6">
        <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 bg-slate-50 p-4 rounded-xl border border-slate-100">
          <label className="text-sm font-semibold text-slate-500 uppercase tracking-wide">
            User ID:
          </label>
          <input
            type="text"
            {...register("username")}
            className="text-lg font-bold text-slate-900 bg-transparent outline-none flex-1"
            readOnly
          />
        </div>

        <div className="flex bg-slate-100 p-1 rounded-xl w-fit">
          <button
            type="button"
            className={`px-6 py-2 rounded-lg font-semibold text-sm transition-all ${settingsPage === "Interests" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
            onClick={() => setSettingsPage("Interests")}
          >
            Interests
          </button>
          <button
            type="button"
            className={`px-6 py-2 rounded-lg font-semibold text-sm transition-all ${settingsPage === "Classes" ? "bg-white text-indigo-600 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
            onClick={() => setSettingsPage("Classes")}
          >
            Classes
          </button>
        </div>

        {settingsPage === "Interests" ? (
          <UserInterestsForm
            register={register}
            interests={interests}
            interestsAppend={interestsAppend}
            interestsRemove={interestsRemove}
            interestsListResponse={interestsListResponse}
          />
        ) : (
          <UserClassesForm
            register={register}
            completedClasses={completedClasses}
            completedClassesAppend={completedClassesAppend}
            completedClassesRemove={completedClassesRemove}
            classListResponse={classListResponse}
            specializationListResponse={specializationListResponse}
          />
        )}

        <input
          type="submit"
          value="Save Changes"
          className="mt-4 bg-indigo-600 text-white py-4 px-6 rounded-xl font-bold hover:bg-indigo-700 transition-colors cursor-pointer shadow-sm hover:shadow-md"
        />
      </form>
    </div>
  );
}
