// Form: the stuff needed
// name, selected lists of classes taken and the difficulty of each class,
// list of skills and their difficultys, selection for CS specialization
// Quarters left till graditiaton

import { useForm, useFieldArray } from "react-hook-form";
import { useEffect, useState } from "react";
import useApiPost from "./useApiPost";
import useApiGet from "./useApiGet";
import ReadCookie from "./readCookie";

export default function UserSettingsForm({ setSettings }) {
  const {
    register,
    control,
    handleSubmit,
    reset, // <-- This function can force-update the entire form at once (Added by Gemini AI)
    formState: { errors },
  } = useForm({
    defaultValues: {
      completedClasses: [],
      strengths: {},
      username: ReadCookie("user_id") || "",
      quartersLeft: 0,
      specialization: "",
    },
  });

  const onSubmit = (data) => {
    setSettings(false);
    console.log("Clean JSON data:", data);
    // if the user is not logged in, save the data to local storage (generated with gemini ai)
    if (!data.username) {
      console.log("No user logged in, saving to local storage");
      localStorage.setItem("userSettings", JSON.stringify(data));
    } else {
      sendUserInfo(data);
    }
  };

  const [settingsPage, setSettingsPage] = useState("Skills");

  const { execute: getUserInfo, response: userInfoResponse } = useApiGet({
    api: "/api/getUserInfo",
  });

  const { fields, append, remove } = useFieldArray({
    control,
    name: "completedClasses",
  });

  const { execute: sendUserInfo, response: setUserInfoResponse } = useApiPost({
    api: "/api/setUserInfo",
  });

  // this gets the class info when the settings page first comes up
  // so we can populate the drop down menu for the user to select
  const { execute: getClassInfo, response: classListResponse } = useApiGet({
    api: "/api/classInfo",
  });

  const {
    execute: getSpecializationInfo,
    response: specializationListResponse,
  } = useApiGet({
    api: "/api/specializationInfo",
  });

  useEffect(() => {
    getClassInfo();
    getSpecializationInfo();
    // Use the ReadCookie helper to get the user_id from document.cookie
    const userId = ReadCookie("user_id");
    getUserInfo({ params: { userid: userId } });
  }, []);

  // This logic was generated by Gemini AI to handle auto-populating saved data
  // When reset(data) is called, it finds all registered inputs matching the
  // keys in your JSON (skills, specialization, and even the 'classes' array)
  // and updates them to match the new values.
  useEffect(() => {
    if (userInfoResponse?.data) {
      reset(userInfoResponse.data);
    } else if (!ReadCookie("user_id")) {
      // If guest user, try to load from local storage (genereated with geminii)
      const localData = localStorage.getItem("userSettings");
      if (localData) {
        console.log("Loading guest settings from local storage");
        reset(JSON.parse(localData));
      }
    }
  }, [userInfoResponse, reset]);

  const strengths = [
    { name: "Math", value: 0 },
    { name: "Algorithms", value: 0 },
    { name: "Data Structures", value: 0 },
    { name: "Programming", value: 0 },
    { name: "Recursion", value: 0 },
  ];

  return (
    <div>
      <h2 className="text-3xl font-bold mb-6">User Settings</h2>
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-6">
        <div className="flex flex-row gap-2">
          <label className="text-xl font-semibold">User ID:</label>
          <input
            type="text"
            {...register("username")}
            className="text-xl font-semibold"
            readOnly
          />
        </div>

        <div className="flex">
          <button
            type="button"
            className="text-xl font-bold outline px-3 rounded-l-md hover:text-blue-700"
            onClick={() => setSettingsPage("Skills")}
          >
            Skills
          </button>
          <button
            type="button"
            className="text-xl font-bold outline px-3 rounded-r-md hover:text-blue-700"
            onClick={() => setSettingsPage("Classes")}
          >
            Classes
          </button>
        </div>

        {settingsPage === "Skills" ? (
          <div className="flex flex-col gap-4">
            <h3 className="text-xl font-semibold mb-2">
              Self-Assessment Skills
            </h3>
            {strengths.map((skill) => (
              <div
                key={skill.name}
                className="flex gap-4 justify-between items-center bg-gray-50 p-3 rounded-lg"
              >
                <label className="font-medium text-gray-700">
                  {skill.name}
                </label>
                <div className="flex gap-3 justify-end items-center">
                  <label className="text-xs text-gray-500">1</label>
                  <input
                    id={skill.name}
                    type="range"
                    min="1"
                    max="5"
                    step="1"
                    className="w-30 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                    {...register(`strengths.${skill.name}`)}
                  />
                  <label className="text-xs text-gray-500">5</label>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            {/* this section was written by gemini ai for the class selection, lke the 
            cards and the add class button and layout. I modified it to fit my needs. */}
            <div className="flex flex-row gap-4 justify-between">
              <div className="flex flex-col gap-2">
                <h3 className="text-xl font-semibold">Specialization</h3>
                <select
                  {...register("specialization")}
                  className="w-64 p-2 bg-gray-50 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                >
                  <option value="">Select a specialization...</option>
                  {specializationListResponse?.data?.map((specialization) => (
                    <option
                      key={specialization.specialization}
                      value={specialization.specialization}
                    >
                      {specialization.specialization}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col gap-2">
                <h3 className="text-xl font-semibold">Quarters Left</h3>

                <input
                  type="number"
                  min="0"
                  {...register("quartersLeft")}
                  placeholder="Enter quarters left..."
                  className="w-32 p-2 bg-gray-50 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                />
              </div>
            </div>

            <div className="flex justify-between items-center mb-2">
              <h3 className="text-xl font-semibold">Classes Taken</h3>
              <button
                type="button"
                onClick={() =>
                  append({ className: "", grade: "", difficulty: 3 })
                }
                className="bg-green-500 text-white px-3 py-1 rounded-md text-sm hover:bg-green-600 transition-colors"
              >
                + Add Class
              </button>
            </div>

            {fields.length === 0 && (
              <div className="py-10 text-center border-2 border-dashed border-gray-200 rounded-xl bg-gray-50 text-gray-400">
                No classes added yet. Click "+ Add Class" to begin.
              </div>
            )}

            <div className="flex flex-col gap-3 max-h-[320px] overflow-y-auto pr-2 custom-scrollbar">
              {fields.map((field, index) => (
                <div
                  key={field.id}
                  className="flex flex-col sm:flex-row gap-4 bg-white p-4 rounded-lg shadow-sm border border-gray-200 items-end"
                >
                  <div className="flex-1 w-full">
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">
                      Class Name
                    </label>
                    <select
                      {...register(`completedClasses.${index}.className`)}
                      className="w-full p-2 bg-gray-50 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                    >
                      <option value="">Select a class...</option>
                      {classListResponse &&
                        classListResponse.data && // Access the 'data' array inside the object
                        Array.isArray(classListResponse.data) &&
                        classListResponse.data.map((course) => (
                          <option
                            key={course.className}
                            value={course.className}
                          >
                            {course.className}
                          </option>
                        ))}
                    </select>
                  </div>

                  <div className="w-full sm:w-24">
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">
                      Grade
                    </label>
                    <input
                      type="text"
                      placeholder="A-"
                      {...register(`completedClasses.${index}.grade`)}
                      className="w-full p-2 bg-gray-50 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                    />
                  </div>

                  <div className="w-full sm:w-40">
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1 text-center">
                      Difficulty
                    </label>
                    <div className="flex gap-2 items-center">
                      <span className="text-xs text-gray-400">1</span>
                      <input
                        type="range"
                        min="1"
                        max="5"
                        {...register(`completedClasses.${index}.difficulty`)}
                        className="w-max h-1.5 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                      />
                      <span className="text-xs text-gray-400">5</span>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => remove(index)}
                    className="p-2 text-red-500 hover:bg-red-50 rounded-md transition-colors"
                    title="Remove Class"
                  >
                    x
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        <input
          type="submit"
          value="Save Settings"
          className="mt-4 bg-blue-600 text-white py-3 px-6 rounded-lg font-bold hover:bg-blue-700 transition-colors cursor-pointer shadow-md"
        />
      </form>
    </div>
  );
}
