import LoginForm from "../Components/LoginForm";
import CreateAccountForm from "../Components/CreateAccountForm";
import { useEffect, useState } from "react";

export default function LoginPage({ setDisplayLoginPage }) {
  const [isRegistering, setIsRegistering] = useState(false);

  // this useEffect was generated by gemini ai
  // this checks if the user presses esc to exit the login page
  useEffect(() => {
    // This function runs every time a key is pressed
    const handleKeyDown = (e) => {
      // We check the "key" property of the event to see if it matches "Escape"
      if (e.key === "Escape") {
        // If it matches, we use the setter function to close the form
        setDisplayLoginPage(false);
      }
    };
    // We tell the browser window to start listening for "keydown" events
    // When any key is pressed, it will now run our 'handleKeyDown' function above
    window.addEventListener("keydown", handleKeyDown);

    // This runs only when the component is removed from the screen (unmounted)
    // It's like hanging up a phone call; we stop listening to save memory and prevent bugs
    return () => window.removeEventListener("keydown", handleKeyDown);
    // The dependency array: This ensures the effect only sets up once
  }, [setDisplayLoginPage]);

  return (
    <div className="fixed inset-0 flex justify-center items-center bg-black/40 backdrop-blur-sm z-50 p-4">
      <div className="relative flex flex-col justify-left z-50 max-w-md mx-auto bg-white p-10 rounded-lg">
        <button
          type="button"
          onClick={() => setDisplayLoginPage(false)}
          className="absolute top-3 right-3 text-gray-400 hover:text-gray-600 text-lg leading-none cursor-pointer"
        >
          ×
        </button>
        {isRegistering ? (
          <CreateAccountForm
            setDisplayLoginPage={setDisplayLoginPage}
            toggleForm={() => setIsRegistering(false)}
            // passing through a function means that the child component can change the state of the parent component
            // without having to know the exact state of the parent component or how to use it
          />
        ) : (
          <LoginForm
            setDisplayLoginPage={setDisplayLoginPage}
            toggleForm={() => setIsRegistering(true)}
          />
        )}
      </div>
    </div>
  );
}
