import { useEffect } from "react";
import UserSettingsForm from "../Components/UserSettingsForm";

export default function UserSettingsPage({ setDisplaySettingsPage }) {
  // this useEffect was generated by gemini ai
  // this checks if the user presses esc to exit the login page
  useEffect(() => {
    // This function runs every time a key is pressed
    const handleKeyDown = (e) => {
      // We check the "key" property of the event to see if it matches "Escape"
      if (e.key === "Escape") {
        // If it matches, we use the setter function to close the form
        setDisplaySettingsPage(false);
      }
    };

    // We tell the browser window to start listening for "keydown" events
    // When any key is pressed, it will now run our 'handleKeyDown' function above
    window.addEventListener("keydown", handleKeyDown);

    // This runs only when the component is removed from the screen (unmounted)
    // It's like hanging up a phone call; we stop listening to save memory and prevent bugs
    return () => window.removeEventListener("keydown", handleKeyDown);
    // The dependency array: This ensures the effect only sets up once
  }, [setDisplaySettingsPage]);

  return (
    <div className="fixed inset-0 flex justify-center items-center bg-slate-900/40 backdrop-blur-md z-50 p-4 transition-all">
      <div className="relative flex flex-col justify-left z-50 w-full max-w-2xl mx-auto bg-white p-8 sm:p-10 rounded-2xl shadow-2xl border border-slate-100">
        <button
          type="button"
          onClick={() => setDisplaySettingsPage(false)}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-full transition-colors leading-none cursor-pointer"
        >
          ✕
        </button>
        <UserSettingsForm setDisplaySettingsPage={setDisplaySettingsPage} />
      </div>
    </div>
  );
}
