
import { useEffect } from "react";
import UserSettingsForm from "../Components/UserSettingsForm";

export default function UserSettingsPage({ setSettings }) {
  
    // this useEffect was generated by gemini ai
  // this checks if the user presses esc to exit the login page
  useEffect(() => {
  // This function runs every time a key is pressed
  const handleKeyDown = (e) => {
    // We check the "key" property of the event to see if it matches "Escape"
    if (e.key === "Escape") {
      // If it matches, we use the setter function to close the form
      setSettings(false);
    }
  };
  // We tell the browser window to start listening for "keydown" events
  // When any key is pressed, it will now run our 'handleKeyDown' function above
  window.addEventListener("keydown", handleKeyDown);

  // This runs only when the component is removed from the screen (unmounted)
  // It's like hanging up a phone call; we stop listening to save memory and prevent bugs
  return () => window.removeEventListener("keydown", handleKeyDown);
  // The dependency array: This ensures the effect only sets up once
}, [setSettings]);


  return (
    <div className="fixed inset-0 flex justify-center items-center bg-black/40 backdrop-blur-sm z-50 p-4">
      <div className="flex flex-col justify-left z-50 max-w-md mx-auto bg-white p-10 rounded-lg">
        <UserSettingsForm />
      </div>
    </div>
  );
}
